<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VAIO" ignored="0" name="Test" tests="4" failures="1" timestamp="14 May 2017 11:47:15 GMT" time="24.125" errors="0">
  <testcase name="login" time="1.751" classname="com.nareshmaven.example.Testng"/>
  <testcase name="customerLogin" time="2.313" classname="com.nareshmaven.example.Testng"/>
  <testcase name="changePassword" time="2.674" classname="com.nareshmaven.example.Testng"/>
  <testcase name="Transfer" time="1.591" classname="com.nareshmaven.example.Testng">
    <failure type="java.lang.AssertionError" message="expected [6] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [4]
	at com.nareshmaven.example.Testng.Transfer(Testng.java:80)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Transfer -->
</testsuite> <!-- Test -->
